### ISSUE TITLE
how i can see the drawing animation like your goku

### ISSUE THREAD

**Issue by KeparYTbcc** [hrshtv/Sketchy-Turtle#3]
![drawing](https://user-images.githubusercontent.com/67996155/127952620-99c87b27-55b2-4b66-b199-71a32139ea57.gif)

**Comment by KeparYTbcc** [comment]
NVM

**Comment by KeparYTbcc** [comment]
but can why make it go faster??

**Comment by hrshtv** [comment]
You can try ways of reducing the number of pixels the turtle has to go to.  
One way to do this would be to make the edges thinner, using something like image erosion (`cv2.erode`)
